//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Office.Tools.Word;
using System.Collections;

namespace NetherlandsExpoBot
{
    public class HashTableElementos
    {
        private Hashtable _controlesHash;
        public HashTableElementos()
        {
            _controlesHash = new Hashtable();
        }

        public void AddControl(RichTextContentControl control)
        {
            _controlesHash.Add(control.Tag, control);
        }

        public RichTextContentControl GetControl(string key)
        {
            return (RichTextContentControl)_controlesHash[key];
        }
    }
}